### ISSUE TITLE
Brew install phantoms no longer maintained

### ISSUE THREAD

**Issue by eli-oat** [springernature/pa11y#121]
Replace with `npm install phantomjs`

**Comment by GlynnPhillips** [comment]
Hi @eli-oat, I know they have in the past been having some issues when installing via `brew` (maybe this is reason enough for the change) but I have not seen anything where they state they will be dropping support for `brew`.

Maybe I have not looked hard enough, but do you have a source I could look at?

**Comment by petetnt** [comment]
When I was setting `pa11y` up (wrote #120), I used `npm` to update my `phantomjs` to version 2 with

```
   npm install phantomjs2 --save
```

Which works well (despite the usual PhantomJS problems on Windows).  

The `README.md` states that `pa11y` requires PhantomJS but it doesn't define which version: v2 contains tons of breaking changes IIRC, (which would explain why I couldn't run it with 1.9 but 2.0 worked fine).

**Comment by rowanmanning** [comment]
Hi @eli-oat, I'm having the same issue as Glynn, I can't find the dropping of support anywhere. Could you provide a link?

@petetnt: ah separate issue, but pa11y _should_ work with `1.9` and `2.0`. Might not be the case. I've opened an issue to investigate: #123

**Comment by rowanmanning** [comment]
I'm going to close this issue for now. If you're able to provide info about the deprecation of Homebrew PhantomJS then we can re-open
