### ISSUE TITLE
pa11y installation issue (Windows)

### ISSUE THREAD

**Issue by kranthi10** [springernature/pa11y#135]
I have cloned pa11y repo locally and I am having trouble with installing dependencies with npm install. It was timing out all the time. npm-debug has following lines as error message.
-- 18 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 23.235.46.162:443

Operaing system: Windows 7 and Node.js version: v5.6.0

**Comment by rowanmanning** [comment]
Hmm, I haven't come across this before. Have you tried cloning a different Node.js project to see if `npm install` works with that? That would tell us whether it's a pa11y issue or the way your npm is set up.

**Comment by rowanmanning** [comment]
I'm going to close this issue for now. If you're still having trouble then feel free to re-open.
