### ISSUE TITLE
What does zero error mean?

### ISSUE THREAD

**Issue by gianluca78** [springernature/pa11y#148]
Hello,
I need a clarification about the meaning of zero errors in the pa11y reports. 
I think that the absence of a criteria from the report of errors could be caused by two different scenarios:

1. the accessibility criteria has been satisfied;
2. the accessibility criteria is not applicable to the webpage examined by pa11y (i.e. I can't search for textual alternative of images if the webpage doesn't include images!)

Is there a way to distinguish between the aforementioned scenarios? How?

Thank you very much!

**Comment by nickcall** [comment]
Hi @gianluca78 - good to hear from you again, glad you're continuing to find pa11y useful :simple_smile:
In order to help us give a good answer, please can you tell us why you need to distinguish between scenario 1 and 2? Currently pa11y only allows for scenario 1, what usage would you have for scenario 2

**Comment by gianluca78** [comment]
Hi @nickcall ,
I just would like to calculate an "accessibility index". For this reason, a website with 0 errors in the scenario 1 is better than a website with no errors in the scenario 2. And the weight of zero errors would be different...

Thanks!

**Comment by nickcall** [comment]
@gianluca78 It sounds like your trying to do some interesting stuff with pa11y!

We're only looking for accessibility errors and not ​_potential_ errors so I'm afraid scenario 2 isn't something we'd want to add support for in pa11y.

Maybe you could process the page separately using another tool, which can analyse how "simple" a page is accessibility-wise? We'd be interested to hear how you achieve this and know the results of your work, which sounds interesting :)
