### ISSUE TITLE
Pa11y for sites on development server

### ISSUE THREAD

**Issue by qaDream77** [springernature/pa11y#90]
I have my development server and my production server. I host my dev sites on the dev server and block all connections to those dev sites from pc that are outside the network.

I am running pa11y on a mac osx which is on the network, the mac can load the site in the browser but when i try to use pa11y, i get 
Error: PhantomJS failed to open "https://dev.test.serv.ca/foobar.html"

Any advice would be greatly appreciated!

**Comment by rowanmanning** [comment]
Hi. A quick test would be to cURL the URL and see what it returns. If cURL can't access the site either, it might mean that something is saved in your browser which is giving you access. If cURL _can_ access the site, there's something wrong with pa11y and we can investigate.

```
curl https://dev.test.serv.ca/foobar.html
```

**Comment by qaDream77** [comment]
First off, thanks for the reply and great work with pa11y, so far I'm loving it.

The site does have a TSLv1.2 cert. Curl printed out the entire page source for me, so it has access to the site. As for pa11y, i am not completely sure yet, i am looking at phantomjs solo atm to see it's debug log. I am not really sure how phantomjs works but i didn't think it was going to an outside server.

**Comment by qaDream77** [comment]
To throw in a few more details. it throws a phantomjs error but when i try a simple phantom script.

var page = require('webpage').create();
page.open('https://dev.test.serv.ca/foobar.html', function () {
    console.log(page.content);
    phantom.exit();
});

It opens the page and prints out the source, this leads me to believe that this an isolated issue related to pa11y and not phantom.

**Comment by rowanmanning** [comment]
Thanks for the extra info @qaDream77, it's helpful and yes it does seem to be pa11y that's at fault. I might write a test case for you when I get time and see if we can isolate the issue. It could be in pa11y, Truffler (a lib that pa11y uses) or even the Node phantomJS client that Truffler uses.

Odd that it works on Windows but not Mac. Silly question, but have you tried trashing your `node_modules` folder and reinstalling them?

**Comment by rowanmanning** [comment]
Sorry, uninstalling and reinstalling pa11y itself.

**Comment by qaDream77** [comment]
Yes, I went so far as to uninstall everything related to pa11y. Node, phantomjs, etc. The issue still persists on OS X.

**Comment by rowanmanning** [comment]
@qaDream77: sorry for the delay, but are you still having this issue?

**Comment by rowanmanning** [comment]
I'm going to close this issue for now. If you're still having problems then feel free to re-open.
