### ISSUE TITLE
Pa11y and Jenkins Integration

### ISSUE THREAD

**Issue by qaDream77** [springernature/pa11y#92]
Just wondering if anyone has looked into this or wants to collaborate on creating a plugin :)

Although currently, i can't even get Jenkins to test a site, it crashes

C:\Program Files (x86)\Jenkins\jobs\plugin test\workspace>pa11y google.ca 
Welcome to Pa11y

 > PhantomJS browser created
 > Testing page: "http://google.ca"

Results for google.ca:
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

However if i create a js file and run "node test.js", i am able to evaluate websites for accessibility issues.

To elaborate, I know that the build should be marked as failure because of the error codes. What i am more curious about is why it doesn't print out any of the results unless i redirect the output to a file.

**Comment by rowanmanning** [comment]
I'm going to close this issue for now as we won't be creating a Jenkins plugin as part of this repository. If you're having issues with Jenkins that you think are related to pa11y (and not the Jenkins setup) then feel free to open another issue.
